In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data-master.csv', sep=';')
df.shape

(1641, 79)

In [7]:
selected_cols_to_analyze = ['Level of Interaction with Disaster', 'Age', 'Usage Duration', 'Frequency of Usage (min) (in month)', 'Fishing Experience', 'Beach']

df = df[selected_cols_to_analyze]
df.columns

Index(['Level of Interaction with Disaster', 'Age', 'Usage Duration',
       'Frequency of Usage (min) (in month)', 'Fishing Experience', 'Beach'],
      dtype='object')

In [17]:
beach_map = {
    1: 'pantai lampuuk',
    2: 'pantai lhoknga',
    3: 'pantai ulee lheue',
    4: 'pantai depok',
    5: 'pantai samas',
}

df['Mapped Beach'] = df['Beach'].map(beach_map)

df.drop(columns=['Beach'], inplace=True)

print('Data cleaned')

Data cleaned

In [20]:
df_pantai_lampuuk = df[df['Mapped Beach'] == 'pantai lampuuk']
df_pantai_lhoknga = df[df['Mapped Beach'] == 'pantai lhoknga']
df_pantai_ulee_lheue = df[df['Mapped Beach'] == 'pantai ulee lheue']
df_pantai_depok = df[df['Mapped Beach'] == 'pantai depok']
df_pantai_samas = df[df['Mapped Beach'] == 'pantai samas']

# Pantai Lampuk

In [22]:
df_pantai_lampuuk.describe()

,Level of Interaction with Disaster,Age,Usage Duration,Frequency of Usage (min) (in month),Fishing Experience
count,426.000000,426.000000,426.000000,426.000000,426.000000
mean,3.802817,39.180751,14.915493,11.516432,15.091549
std,2.291384,9.744390,8.235784,8.690547,8.698807
min,0.000000,20.000000,1.000000,1.000000,2.000000
25%,2.000000,30.000000,8.000000,3.000000,8.000000
50%,4.000000,39.000000,13.500000,12.000000,13.000000
75%,5.000000,47.000000,20.000000,16.000000,21.000000
max,8.000000,62.000000,43.000000,30.000000,43.000000

In [23]:
pantai_lampuuk_characteristics_input = {
    'Level of Interaction with Disaster': 3.8,
    'Age': 39.18,
    'Usage Duration': 14.91,
    'Frequency of Usage (min) (in month)': 11.51,
    'Fishing Experience': 15.09
}

# Pantai Lhoknga

In [24]:
df_pantai_lhoknga.describe()

,Level of Interaction with Disaster,Age,Usage Duration,Frequency of Usage (min) (in month),Fishing Experience
count,687.000000,687.000000,687.000000,687.000000,687.000000
mean,1.272198,42.742358,17.983988,5.247453,17.918486
std,1.784326,8.649761,8.050390,7.029502,8.152826
min,0.000000,26.000000,4.000000,1.000000,3.000000
25%,0.000000,36.000000,11.000000,2.000000,11.000000
50%,1.000000,42.000000,17.000000,3.000000,17.000000
75%,2.000000,50.000000,22.000000,4.000000,22.000000
max,8.000000,60.000000,38.000000,30.000000,38.000000

In [25]:
pantai_lhoknga_characteristics_input = {
    'Level of Interaction with Disaster': 1.27,
    'Age': 42.74,
    'Usage Duration': 17.98,
    'Frequency of Usage (min) (in month)': 5.24,
    'Fishing Experience': 17.91
}

# Pantai Ulee Lheue

In [26]:
df_pantai_ulee_lheue.describe()

,Level of Interaction with Disaster,Age,Usage Duration,Frequency of Usage (min) (in month),Fishing Experience
count,436.000000,436.000000,436.000000,430.000000,436.000000
mean,3.594037,48.288991,19.752294,4.272093,21.442661
std,1.827720,5.949903,4.844537,5.672320,4.958579
min,0.000000,27.000000,5.000000,1.000000,5.000000
25%,2.000000,45.000000,17.000000,2.000000,18.000000
50%,4.000000,49.000000,20.000000,3.000000,23.500000
75%,5.000000,53.000000,23.000000,4.000000,25.000000
max,8.000000,60.000000,36.000000,30.000000,35.000000

In [27]:
pantai_ulee_lheue_characteristics_input = {
    'Level of Interaction with Disaster': 3.59,
    'Age': 48.28,
    'Usage Duration': 19.75,
    'Frequency of Usage (min) (in month)': 4.27,
    'Fishing Experience': 21.44
}

# Pantai Depok

In [28]:
df_pantai_depok.describe()

,Level of Interaction with Disaster,Age,Usage Duration,Frequency of Usage (min) (in month),Fishing Experience
count,60.000000,60.000000,60.000000,59.000000,60.000000
mean,4.433333,41.266667,12.516667,2.627119,15.583333
std,2.374773,7.668705,5.273829,1.388354,5.929792
min,2.000000,22.000000,2.000000,1.000000,2.000000
25%,3.000000,38.000000,9.500000,1.000000,10.000000
50%,4.000000,43.000000,15.000000,2.000000,15.000000
75%,5.000000,46.000000,15.000000,4.000000,20.000000
max,15.000000,60.000000,20.000000,5.000000,25.000000

In [29]:
pantai_depok_characteristics_input = {
    'Level of Interaction with Disaster': 4.43,
    'Age': 41.26,
    'Usage Duration': 12.51,
    'Frequency of Usage (min) (in month)': 2.62,
    'Fishing Experience': 15.58
}

# Pantai Samas

In [30]:
df_pantai_samas.describe()

,Level of Interaction with Disaster,Age,Usage Duration,Frequency of Usage (min) (in month),Fishing Experience
count,32.000000,32.000000,32.000000,32.000000,32.000000
mean,2.125000,28.937500,4.968750,2.437500,6.343750
std,0.941858,5.913012,2.520681,1.389767,3.307951
min,1.000000,19.000000,1.000000,1.000000,1.000000
25%,1.000000,24.000000,3.000000,1.000000,5.000000
50%,2.000000,28.000000,5.000000,2.000000,6.000000
75%,3.000000,32.000000,7.000000,4.000000,7.000000
max,5.000000,40.000000,10.000000,5.000000,15.000000

In [31]:
pantai_samas_characteristics_input = {
    'Level of Interaction with Disaster': 2.12,
    'Age': 28.93,
    'Usage Duration': 4.96,
    'Frequency of Usage (min) (in month)': 2.43,
    'Fishing Experience': 6.34
}